openapi: 3.0.1
info:
  title: test-bed
  x-cortex-tag: test-bed
  x-cortex-git:
    github:
      repository: xycia-cortex/Jelly-Bean
      basepath: Catalog
  x-cortex-custom-metadata:
    cortex-template-version: 0.1.2
    cortex-generated-timestamp: 2025-08-15T19:58:37.587825562
